name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/xwxqwqpwpawa/kernel_xiaomi_raphael_4.19
          kernel-branch: lineage-23.0_raphael
          config: raphael_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 16
          aosp-clang-version: r547379
